Name:           fcitx5-hud-paper
Version:        1.0
Release:        1%{?dist}
Summary:        Hud Paper fcitx5 themes (light and dark)

License:        MIT
URL:            https://github.com/Maomaokuxs/rpmbuild
Source1:        https://raw.githubusercontent.com/Maomaokuxs/rpmbuild/main/assets/fcitx5-hud-paper/hud-paper/theme.conf#/hud-paper-theme.conf
Source2:        https://raw.githubusercontent.com/Maomaokuxs/rpmbuild/main/assets/fcitx5-hud-paper/hud-paper/panel.svg#/hud-paper-panel.svg
Source3:        https://raw.githubusercontent.com/Maomaokuxs/rpmbuild/main/assets/fcitx5-hud-paper/hud-paper/highlight.svg#/hud-paper-highlight.svg
Source4:        https://raw.githubusercontent.com/Maomaokuxs/rpmbuild/main/assets/fcitx5-hud-paper/hud-paper-dark/theme.conf#/hud-paper-dark-theme.conf
Source5:        https://raw.githubusercontent.com/Maomaokuxs/rpmbuild/main/assets/fcitx5-hud-paper/hud-paper-dark/panel.svg#/hud-paper-dark-panel.svg
Source6:        https://raw.githubusercontent.com/Maomaokuxs/rpmbuild/main/assets/fcitx5-hud-paper/hud-paper-dark/highlight.svg#/hud-paper-dark-highlight.svg

BuildArch:      noarch
Requires:       fcitx5

%description
Hud Paper is a pair of self-made fcitx5 ClassicUI themes
(light: hud-paper, dark: hud-paper-dark) generated by
sync-waybar.sh from the Waybar/hellwal palette.
Paper background with accent selection block.

%prep

%build

%install
mkdir -p %{buildroot}%{_datadir}/fcitx5/themes/hud-paper
mkdir -p %{buildroot}%{_datadir}/fcitx5/themes/hud-paper-dark
install -m 644 %{SOURCE1} %{buildroot}%{_datadir}/fcitx5/themes/hud-paper/theme.conf
install -m 644 %{SOURCE2} %{buildroot}%{_datadir}/fcitx5/themes/hud-paper/panel.svg
install -m 644 %{SOURCE3} %{buildroot}%{_datadir}/fcitx5/themes/hud-paper/highlight.svg
install -m 644 %{SOURCE4} %{buildroot}%{_datadir}/fcitx5/themes/hud-paper-dark/theme.conf
install -m 644 %{SOURCE5} %{buildroot}%{_datadir}/fcitx5/themes/hud-paper-dark/panel.svg
install -m 644 %{SOURCE6} %{buildroot}%{_datadir}/fcitx5/themes/hud-paper-dark/highlight.svg

%files
%{_datadir}/fcitx5/themes/hud-paper/
%{_datadir}/fcitx5/themes/hud-paper-dark/

%changelog
* Sun Sep 20 2026 Maomaokuxs <biyuanh@qq.com> - 1.0-1
- Initial package (hud-paper + hud-paper-dark from Documents/fcitx5)
