%global debug_package %{nil}
%global __provides_exclude ^(%{_libdir}/%{name}/.*\.so)
%global __requires_exclude ^(libmpv|libflutter|libdart|libapp).*

Name:           splayer
Version:        3.1.1
Release:        1%{?dist}
Summary:        Splayer 应用

License:        Unknown
URL:            https://github.com/SPlayer-Dev/SPlayer
Source0:        https://github.com/SPlayer-Dev/SPlayer/releases/download/v3.1.1/splayer-3.1.1-x64.tar.gz
Source1:        https://raw.githubusercontent.com/Maomaokuxs/rpmbuild/main/assets/splayer-icon.png

BuildRequires:  desktop-file-utils
BuildRequires:  chrpath
BuildRequires:  rpm-build

%description
Splayer 第三方应用。

%prep
mkdir -p %{name}-%{version}
cd %{name}-%{version}

%build

%install
mkdir -p %{buildroot}%{_libdir}/%{name} %{buildroot}%{_bindir} %{buildroot}%{_datadir}/applications
tar xzf %{SOURCE0} -C %{buildroot}%{_libdir}/%{name} --strip-components=1
for f in %{buildroot}%{_libdir}/%{name}/SPlayer %{buildroot}%{_libdir}/%{name}/lib/*.so; do
    chrpath -r '$ORIGIN/lib' "$f" 2>/dev/null || true
done
chmod +x %{buildroot}%{_libdir}/%{name}/SPlayer
ln -s %{_libdir}/%{name}/SPlayer %{buildroot}%{_bindir}/%{name}
mkdir -p %{buildroot}%{_datadir}/icons/hicolor/256x256/apps
install -m 644 %{SOURCE1} %{buildroot}%{_datadir}/icons/hicolor/256x256/apps/%{name}.png
mkdir -p %{buildroot}%{_datadir}/applications
cat > %{buildroot}%{_datadir}/applications/%{name}.desktop <<DESKEOF
[Desktop Entry]
Name=Splayer
Comment=Splayer 应用
Exec=%{name}
Icon=%{name}
Terminal=false
Type=Application
Categories=Utility;
StartupWMClass=Splayer
DESKEOF
%check
desktop-file-validate %{buildroot}%{_datadir}/applications/%{name}.desktop

%files
%{_bindir}/%{name}
%{_libdir}/%{name}/
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/256x256/apps/%{name}.png

%changelog
* Thu Jul 09 2026 Maomaokuxs <biyuanh@qq.com> - 3.1.1-1
- Auto-generated by opt-mgr build
